# build and deploy on push on every branch
name: Zola Deploy to Pages
on: push

jobs:
  build:
    name: shalzz/zola-deploy-action
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Build and deploy'
        uses: shalzz/zola-deploy-action@master
        env:
          PAGES_BRANCH: gh-pages
          BUILD_DIR: .
          BUILD_FLAGS: --drafts
          TOKEN: ${{ secrets.DEPLOY }}

